### ISSUE TITLE
Can't import YAML lists

### ISSUE THREAD

**Issue by morena** [Modularr/YAML-FrontMatter#17]
Hi, I'm trying to read meta data from a markdown file and I am not able to read lists (the Tags in this case), can you help?
This is the example I am using
`comments: true
date: 2005-09-16 17:20:42+00:00
layout: post
slug: title-sample
title: Title Sample
wordpress_id: 8
tags:
- press`

**Comment by mre** [comment]
Hi. 😄  I'm not the maintainer of the project, but one thing I noticed is that your formatting is broken.
Can you try putting three backticks at the beginning and end of your meta data? Like so:

    ```yaml
    comments: true
    date: 2005-09-16 17:20:42+00:00
    layout: post
    slug: title-sample
    title: Title Sample
    wordpress_id: 8
    tags:
    - press
    ```

This would greatly help to identify the problem.

Which Operating system do you have?
What is your PHP version?
What is the output of `php -m`?

**Comment by morena** [comment]
Hi :) Unfortunately that does not help, the file meta data is prefixed by --- (I trimmed it but it displays like this
`---
comments: true
date: 2005-09-16 17:20:42+00:00
layout: post
slug: title-sample
title: Title Sample
wordpress_id: 8
tags:
- press
---`
 
but if I swap --- with ``` the parser does not recognise the meta data at all and it includes it in content. I am using macOS Sierra 10.12.4 , PHP version is 5.5.3


pnp -m output below
`[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dom
ereg
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
imap
json
ldap
libxml
mbstring
mcrypt
mysql
mysqli
openssl
pcre
PDO
pdo_mysql
pdo_pgsql
pdo_sqlite
pgsql
Phar
posix
Reflection
session
SimpleXML
soap
sockets
SPL
sqlite3
standard
tokenizer
xml
xmlreader
xmlwriter
xsl
yaz
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache

`

**Comment by morena** [comment]
sorry, trying to format my post using the code tags but it's just not working :(

**Comment by mre** [comment]
It's fine, no worries. 😉 
You could try to install the PHP yaml extension.
If you have [homebrew](https://brew.sh/), the command is ```brew install php55-yaml```.
Afterwards you can check if it's working with ```php -m | grep yaml```. It should print "yaml". Then you can try again.

**Comment by bmcminn** [comment]
YAML samples on Github work best if you leave a space after the lang spec:


    ```yaml
    ---
    test: blah
    ```

The other option is to just indent your source sample 4 spaces and Github will treat it as preformatted text.

-----

Back to the issue, if you aren't able to parse the file, you  may want to test that your front matter data is valid YAML: http://www.yamllint.com/

Just checked your sample and it is valid. 

You can also try using the array brackets syntax to see if that fixes the issue:

```yaml
---
tags: [ test, bracket, syntax ]
---
Your page content here
```

**Comment by Blaxus** [comment]
The Yaml Parser is only basic. **It doesn't parse lists, specifically because it doesn't parse multi-line.** Normally a proper Yaml parser is used, it only falls back to the basic parser if you don't have a default parser available in PHP.

**Switching to Symfony Yaml is on my to-do.** Which will have **lists available**, and should turn the yaml block into a full blown associative array. I'm not surprised it doesn't work, because it's not a real parser. It does the basics, which is fine for most cases. But in this case you'll run into issues.

It was bound to happen though. When I wrote this I just needed something quick and easy. But I have been meaning to upgrade to a full yaml-parser.

**Comment by mre** [comment]
@Blaxus doesn't it use the pecl yaml extension if it's available? Looked at the source code and thought that might be enough to install that. Hence my last comment.

**Comment by Blaxus** [comment]
@mre Yes it does, but the basic parser is what most people use. Adding the PECL was an easy fix for people who don't want to use the limited parser and know what they are doing but it's not really a general purpose fix. It still needs replacing. After 2 years of using a Frontmatter parser myself, I can definitively see myself using more then basic variables.

**Comment by Blaxus** [comment]
After some testing with your example I've managed to get a pretty good result with [Symfony Yaml](http://symfony.com/doc/current/components/yaml.html), I even managed to figure out a way to ignore the first triple dash. I'll probably have to completely reorganize the class, so under the hood it will likely be different but I want to keep the package implementation the same, maybe a few option additions (custom seperator/preffered parser/optionally auto-parse Markdown) later down the line, but I'll try not to break anything 😄
```yaml
comments: true
date: 2005-09-16 17:20:42+00:00
layout: post
slug: title-sample
title: Title Sample
wordpress_id: 8
tags:
- foo
- bar
bar: { foo: bar, bar: baz }
bar2:
    foo: bar
    bar: baz
---
<h1>Text Here</h1>
<p>content</p>
```
```php
Array
(
    [content] => <h1>Text Here</h1>
<p>content</p>
    [comments] => 1
    [date] => 1126891242
    [layout] => post
    [slug] => title-sample
    [title] => Title Sample
    [wordpress_id] => 8
    [tags] => Array
        (
            [0] => foo
            [1] => bar
        )
    [bar] => Array
        (
            [foo] => bar
            [bar] => baz
        )
    [bar2] => Array
        (
            [foo] => bar
            [bar] => baz
        )
```

**Comment by Blaxus** [comment]
It should work now. If anything breaks let me know.

**Comment by morena** [comment]
Thanks everyone who has commented on this and offered help! Thanks @Blaxus for enhancing the tool. I will give it a go and let you know if I have issues. Thanks
