### ISSUE TITLE
Break compatibility from 1.2.x

### ISSUE THREAD

**Issue by leplastic** [Modularr/YAML-FrontMatter#19]
Hi. The library was updated a few days ago, but it breaks compatibility from 1.2.x version. So far, I noticed two problems:

- lack of ``fetchKeys`` function (although the ``data`` variable is public, I think the method could be there to ensure compatibility with version 1.x, and maybe removed in 2.x if you like)
- the constructor doesn't accept the contents of file anymore (if you try to pass contents of file to the constructor instead of the file path, ``$document`` variable won't have a value and causes problems later. This can also be confirmed by running your unit test). One idea could be creating factory/static methods to build a customized instance of your FrontMatter, for example: ``FrontMatter::loadFromFile($filePath)`` and ``FrontMatter::loadFromMarkdownContents($contents)``, instead of exposing the constructor.

I think these issues are easy to solve, but let me know if you need help, I can also submit a PR.

**Comment by Blaxus** [comment]
Thanks for pointing it out. _fetchkeys wasn't supposed to be removed_, I probably didn't see it because I personally don't use it that much. And I may have glanced at the input method. Since I went the easy way and simply used file_get_contents I forgot that you could actually simply pass a string.

**Comment by Blaxus** [comment]
Should be fixed now, feel free to let me know if anything else is off.
